### ISSUE TITLE
When running tests another programme seems to run, making the test slow  

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#11]
@yulqen I've got a situation at the moment where if I run any of my tests another (complete separate programme) seems to execute at the same time. I can't figure out what's making this happen. The same thing happens, no matter what test I run. Its causing the tests to all be very slow. Grateful for your help on this. Cheers, Will.

**Comment by yulqen** [comment]
@banillie What tells you that another program is running? Another test? Have stepped through with the debugger? Might need a screenshare.

**Comment by yulqen** [comment]
You probably have code that executes something at global level in one of your modules. Remember that just importing from a module calls all the code at global level. Move everything into functions or classes.

**Comment by banillie** [comment]
@yulqen you were bang on again of course. Had my modules set up wrong and they were executing code unnecessarily. Have just done some useful refactoring. cheers.
