### ISSUE TITLE
Tidying git repository 

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#14]
@yulqen quick question hopefully. 

I don't think the analysis_engine.egg_info file needs to be in my repo. Is the best way to remove it as you would for any other file via `git rm -r --cached .egg_info`. Just checking as it's part of the PyPI package and I didn't want to do anything rash. 

Thanks, Will

**Comment by yulqen** [comment]
Yep, you need to stop tracking these files with git. `git rm --cached` I think is the answer, but Google it to check Will.

**Comment by banillie** [comment]
Thanks Matt. Done.
