### ISSUE TITLE
Change tests data structure to use pickle file

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#17]
Change how test data is stored. Place all test data into a pickle file and then call this for all tests. 
Benefits:
- can slash and burn most test excel files. 
- don't need to keep creating and update test files, if required by corresponding change in code. 
- will be faster to run tests and refactor code.
- will be more aligned to how analysis_engine runs. 
Disbenefits:
- think that it might be a security issue for others to download a pickle file. But are there ways around this? one of the initial tests could create a local version of the pickle file from a masters excel doc, and then there would be no need for the pickle file to push up to remote repo? 

@yulqen would appreciate your thoughts on the above. Cheers.

**Comment by yulqen** [comment]
I would look at using JSON instead of pickle. It's language agnostic, human-readable and more secure. There is a good JSON module in the Python standard library that does everything you need. Have a look and see what you think.

**Comment by banillie** [comment]
Brilliant. Thanks @yulqen

**Comment by banillie** [comment]
Closing as refactor of tests using pickle file complete. But .... next step is JSON.
