### ISSUE TITLE
loading to pypi

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#18]
@yulqen still get an error when doing `twine upload dist/*` stating that dist already exists. I'm getting around it with the command `twine upload --skip-existing dist/*` but could you remind me what I need to do permanently. Ta!

**Comment by yulqen** [comment]
The `twine upload` command takes a path to the files that need to be uploaded as its first argument. Do a `ls dist/` to see what files are in there. I bet you have previous versions of sdist files in there. PyPi only lets you upload the latest version - when you do `twine upload dist/*` the star means "all files inside the dist directory". Either change the command to `twine dist/analysis_engine_v1.0.2` or whatever is the latest, or clear out the `dir` directory before doing `python setup.py ....` step that comes before.

**Comment by yulqen** [comment]
The second option is recommended.

**Comment by banillie** [comment]
Yeah all the old versions are in `dist/` should I just navigate to dist/ and do a `rm *`.

**Comment by yulqen** [comment]
You don't even need to navigate! But yes.

**Comment by banillie** [comment]
Done.
