### ISSUE TITLE
Issues from ver 0.0.10 testing

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#19]
`risks`  fixed. Test with ver 0.0.11 when released.  **DONE**
`query` fixed. Test with ver 0.0.11 when released.   **DONE**
`dandelion` fixed. Test with ver 0.0.11 when released. **DONE**
`matrix` not working don't yet have a time frame for completion. to be set by team. 
`dashboards` working but, need user messaging to help ensure correct master file in the input folder. for ver 0.0.12 **DONE**
`speedials` and `summaries` same as for dashboards user messaging to help ensure summary_temp doc in input folder. for ver 0.0.12 **DONE**

Testing raised issue with rendering process and use of pdf2image raising the following error

```pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?```

good place to start answering this is here [https://stackoverflow.com/questions/53481088/poppler-in-path-for-pdf2image  
](url)

@yulqen would be grateful for your thoughts on this. The team needs to be able to simply install necessary requirements as part of the pip install analysis_engine process and it's not ideal if they need to mess around with paths. I don't have this issue on Ubuntu. **DONE** manual fix was necessary

**Comment by yulqen** [comment]
https://pypi.org/project/pdf2image/

Windows requires manual installation of this package. Don't think you have much choice. How important is pdf2image? I remember you mentioning it re JPGs or something.

**Comment by banillie** [comment]
Yeah it's pretty important. It keeps the rendering of graphical images to a high quality. I could find another solution/package for helping me with this, but I don't remember seeing any other obvious solutions when I was working onto it! 
How difficult will it be to get the team to do it manually? Would you be able to do a demo for me?

**Comment by yulqen** [comment]
I'm sure I could.

**Comment by yulqen** [comment]
Try this:

- on Windows, download zip of poppler release from https://github.com/oschwartz10612/poppler-windows/releases/download/v21.03.0/Release-21.03.0.zip
- unzip and move the whole directory to wherever you want (C:\ or something). It doesn't matter - just remember where it is, and not recommended to leave it in Downloads
- Inside that directory is a bin directory. You need to add that to PATH. https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
- Install pdf2image with pip

Let me know if further problems.

**Comment by banillie** [comment]
Yeap that worked. Need to do a bit of further testing/implementation with the laptops for the rest of the team, but hopefully should be resolved.

**Comment by banillie** [comment]
Two outstanding actions before closing:
- Update guidance and document on poppler instalment requirements. 
- matrix work not yet progressed.

**Comment by banillie** [comment]
Documentation update done.
