### ISSUE TITLE
Requirements.txt not read when doing update

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#28]
Recently published a new version of AE. Required a new package, which was included in requirement.txt but this wasn't installed as part of update. Need to research what the normal / expected behaviour is for this type of scenario.

**Comment by yulqen** [comment]
Packages need to be in `setup.py` for PyPI/`pip` builds. Is that the issue?

**Comment by banillie** [comment]
Thanks @yulqen. I should have remembered that!
