### ISSUE TITLE
adding docx library

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#3]
@hammerheadlemon I need to add the docx library to my .venv. Just wanted to check that its ok for me to install as usual - I could do via via the pycharm project interpreter window or via pip install docx command, and that once I've done this I then update my requirements.txt file with docx. Whats the best method for updating the requirements.txt file? thanks.

**Comment by hammerheadlemon** [comment]
Yep, that would be the way. Just add either with the + button in Pycharm, or do pip install docx in the terminal, or add it to the requirements file, then doing pip install -r. However you so it, yes, just ensure theres an entry in the requirements file for it.

**Comment by banillie** [comment]
@hammerheadlemon thanks. Done. Please could you check if the requirements.txt has been updated correctly (latest version pushed up to git).

**Comment by hammerheadlemon** [comment]
Yeah, looks great.
