### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by hammerheadlemon** [banillie/analysis_engine#6]
It looks from the docs like you create a new section like this:

```
new_section = document.add_section(WD_SECTION.NEW_PAGE)
new_section.orientation = WD_ORIENT.LANDSCAPE
# Do whatever work you need to do here....
new_section2 = document.add_section(WD_SECTION.NEW_PAGE)
new_section2.orientation = WD_ORIENT.PORTRAIT
```

**Comment by banillie** [comment]
Hi Matt, thanks for this and sorry for not replying sooner. Yes this was very helpful. I ended up using this code:

`new_section = doc.add_section(WD_SECTION_START.NEW_PAGE)
        new_width, new_height = new_section.page_height, new_section.page_width
        new_section.orientation = WD_ORIENT.LANDSCAPE
        new_section.page_width = new_width
        new_section.page_height = new_height`
