### ISSUE TITLE
set column widths in python docx table 

### ISSUE THREAD

**Issue by banillie** [banillie/analysis_engine#7]
For the life of me I can't find the way you successfully set table column widths. There is quite a lot out there on this, but none of the proposed solutions seemed to work even if I cut and paste code to test it! Matt Lemon, what do you think? 

Here's some of the links I've been working with:
https://stackoverflow.com/questions/43051462/python-docx-how-to-set-cell-width-in-tables
https://stackoverflow.com/questions/43749177/python-docx-table-column-width

Note: working with libreoffice and one of links above mentions there might be some differences in output between libreoffice and word, but not easy for me to test.

**Comment by banillie** [comment]
But I am saving outputs as docx files. So maybe last point not relevant.

**Comment by hammerheadlemon** [comment]
Will have a look later @banillie.

**Comment by hammerheadlemon** [comment]
I'd need to have a look at at least the relevant section of your code where you are trying to do this.  Where in `analysis_engine` is this being done? (You can create links to lines of code in Github which makes it easy. I think you just click on the link number and you get a menu to copy the location).

**Comment by banillie** [comment]
https://github.com/banillie/analysis_engine/blob/master/project_summaries/tables.py#L1

I've got some generic code here where I've just being trying to alter the column width without success. Thanks.

**Comment by banillie** [comment]
Hi @hammerheadlemon if you could look at this reasonably soon that would be great? This is the last bit of coding I’d like to do in my current sprint on project summary sheets. Cheers.

**Comment by hammerheadlemon** [comment]
Will do my best today - will let you know how I get on.

**Comment by banillie** [comment]
@hammerheadlemon thank you. This bug is bugging me!

**Comment by hammerheadlemon** [comment]
`set_col_widths()` moved up the file, but this is essentially the same:

```python
from docx import Document
from docx.shared import Pt, Inches


def set_col_widths(t):
    widths = (Inches(1), Inches(1), Inches(0.2), Inches(1), Inches(1))
    for row in t.rows:
        for idx, width in enumerate(widths):
            row.cells[idx].width = width


def table():
    doc = Document()

    font = doc.styles["Normal"].font
    font.name = "Arial"
    font.size = Pt(10)

    heading = "How do you change widths?"
    doc.add_paragraph().add_run(heading).bold = True

    table = doc.add_table(rows=1, cols=5)
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Milestone'
    hdr_cells[1].text = 'Date'
    hdr_cells[2].text = 'Change from Lst Qrt'
    hdr_cells[3].text = 'Change from BL'
    hdr_cells[4].text = 'Notes'

    for i in range(0, 10):
        row_cells = table.add_row().cells
        row_cells[0].text = 'h'
        row_cells[1].text = 'e'
        row_cells[2].text = 'l'
        row_cells[3].text = 'l'
        row_cells[4].text = 'oooo'

    set_col_widths(table)

    doc.save("table.docx")


table()
```

The underlying XML is being set correctly, but LibreOffice Writer does not appear to be respecting it. MS Word *does* though in my test. I guess that's the most important thing?? Pain for testing for you though - I had to test by emailing the output file to my work account.

**Comment by banillie** [comment]
Excellent thanks Matt. Yes it works in word but not libreoffice, which is why I couldn't see it on my linux machine!
